const { tag } = require('../../utils/mention');
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function getTarget(ctx){
  let t=null;
  try{ if(ctx.getMentionedOrQuoted) t=ctx.getMentionedOrQuoted(); }catch(e){}
  if(!t && ctx.mentioned && ctx.mentioned[0]) t=ctx.mentioned[0];
  if(!t && ctx.msg){ try{
    const m=ctx.msg.message||{};
    const ci=(m.extendedTextMessage&&m.extendedTextMessage.contextInfo)||(m.imageMessage&&m.imageMessage.contextInfo)||(m.videoMessage&&m.videoMessage.contextInfo)||null;
    if(ci&&ci.participant) t=ci.participant;
  }catch(e){} }
  if(t && t===ctx.sender) t=null;
  return t||null;
}
function fill(tpl,a,b){return String(tpl).split('{a}').join(tag(a)).split('{b}').join(b?tag(b):'alguem');}
async function act(ctx,w,al){ const t=getTarget(ctx); const text=fill(pick(t?w:al),ctx.sender,t); await ctx.reply(text,{mentions:t?[ctx.sender,t]:[ctx.sender]}); }
function cmd(n,al,w,a){return{name:n,aliases:al||[],category:"diversao",description:n,handler:async(ctx)=>act(ctx,w,a)};}
module.exports=[
cmd("abracarforte",[],["💪 {a} deu um ABRACO FORTE em {b}!","🤗 {a} apertou {b} num abraco de urso!"],["💪 {a} abraçou o travesseiro!","🤗 {a} precisa de um abraco"]),
cmd("acenar",[],["👋 {a} acenou pra {b}!","🙋 {a} mandou um aceno pra {b}!"],["👋 {a} acenou pro grupo!","🙋 {a} esta acenando"]),
cmd("admirar",[],["😍 {a} admirou {b}!","🌟 {a}: {b} e demais!"],["😍 {a} em modo admiracao","🌟 {a} deu wow no dia"]),
cmd("agradecer",[],["🙏 {a} agradeceu {b}!","💖 {a}: obrigado, {b}!"],["🙏 {a} agradeceu a vida","💖 {a} modo gratidao"]),
cmd("alien",["et"],["👽 {a} abduziu {b} por 3s!","🛸 {a} fez contato ET com {b}!"],["👽 {a} modo alien","🛸 {a} espera a nave"]),
cmd("aluno",[],["🎓 {a} colocou {b} na carteira!","📚 {a}: atencao, aluno {b}!"],["🎓 {a} abriu o caderno","📚 {a} na aula do chat"]),
cmd("amo",[],["❤️ {a} disse que AMA {b}!","💕 {a} mandou amor pra {b}"],["❤️ {a} clima de amo","💕 {a} espalhou carinho"]),
cmd("amor",["love"],["💘 {a} mandou amor pra {b}!","🌹 {a} declarou amor pra {b}"],["💘 {a} espalhou amor","🌹 {a} romantico hoje"]),
cmd("animal",["bicho","pet"],["🐶 {a} fez carinho de pet em {b}!","🐾 {a} adotou {b} como mascote"],["🐶 {a} modo animal","🐾 {a} miou no chat"]),
cmd("aplaudir",[],["👏 {a} aplaudiu {b}!","🎉 {a}: bravo, {b}!"],["👏 {a} aplaudiu o grupo","🎉 {a}: bravo!"]),
cmd("apoiar",[],["🤝 {a} apoiou {b}!","💪 {a}: conta comigo, {b}!"],["🤝 {a} modo apoio","💪 {a} torcida do grupo"]),
cmd("aviao",["plane"],["✈️ {a} embarcou {b}!","🛫 {a} e {b} decolaram"],["✈️ {a} no portao","🛫 {a} decolou na ideia"]),
cmd("bebida",["drink"],["🧃 {a} ofereceu bebida pra {b}!","🍻 {a} brindo com {b}"],["🧃 {a} abriu a geladeira","🍻 {a} brindo com o grupo"]),
cmd("cafe",["coffee"],["☕ {a} preparou cafe pra {b}!","🍵 {a}: seu cafe, {b}!"],["☕ {a} passou o cafe","🍵 {a} tomou um gole"]),
cmd("cantar",[],["🎤 {a} cantou pra {b}!","🎶 {a} dedicou a musica a {b}"],["🎤 {a} abriu o microfone","🎶 {a} cantou no banho"]),
cmd("carregar",[],["🏋️ {a} carregou {b}!","💪 {a} levantou {b}"],["🏋️ {a} treinou carga","💪 {a} levantou o sofa"]),
cmd("carro",["car"],["🚗 {a} deu volta com {b}!","🚕 {a}: sobe, {b}!"],["🚗 {a} ligou o motor","🚕 {a} de motorista"]),
cmd("casa",["home"],["🏠 {a} convidou {b} pra casa!","🏡 {a}: passa la, {b}!"],["🏠 {a} arrumou a casa","🏡 {a} abriu as janelas"]),
cmd("chorar",[],["😢 {a} chorou com {b}!","😭 {a} e {b} lagrima sincronizada"],["😢 {a} chorou no canto","😭 {a} modo lagrima"]),
cmd("chuva",["rain"],["🌧️ {a} e {b} na chuva!","☔ {a} deu guarda-chuva pra {b}"],["🌧️ {a} modo chuva","☔ {a} abriu o guarda-chuva"]),
cmd("comida",["food","comer"],["🍕 {a} ofereceu comida pra {b}!","🍔 {a}: come, {b}!"],["🍕 {a} abriu o cardapio","🍔 {a} comeu um lanche"]),
cmd("coracao",["heart"],["❤️ {a} mandou coracao pra {b}!","💕 {a} encheu {b} de coracoes"],["❤️ {a} espalhou coracoes","💕 {a} cheio de coracao"]),
cmd("criticar",[],["📝 {a} criticou {b} de leve!","😏 {a}: {b}, da pra melhorar kkk"],["📝 {a} criticou o clima","😏 {a} modo critico kkk"]),
cmd("cumprimentar",[],["🤝 {a} cumprimentou {b}!","👋 {a}: eae, {b}!"],["🤝 {a} cumprimentou o grupo","👋 {a}: eae, pessoal!"]),
cmd("cutucar",[],["👉 {a} cutucou {b}!","😂 {a} cutucou {b} ate reagir"],["👉 {a} cutucou o ar","😂 {a} cutucou o sofa"]),
cmd("danca",["dance"],["💃 {a} dancou pra {b}!","🕺 {a} puxou {b} pra pista"],["💃 {a} ligou o som","🕺 {a} na pista solo"]),
cmd("dancar",[],["🕺 {a} dancou com {b}!","💃 {a} e {b}: duo!"],["🕺 {a} dancou sozinho","💃 {a} duo com a sombra"]),
cmd("desafiar",[],["⚔️ {a} desafiou {b}!","🏆 {a}: topa, {b}?"],["⚔️ {a} procura oponente","🏆 {a} desafio ao grupo"]),
cmd("desculpar",[],["😔 {a} pediu desculpas pra {b}","🙏 {a}: me perdoa, {b}?"],["😔 {a} pediu desculpas ao chat","🙏 {a}: me perdoa, universo"]),
cmd("dinheiro",["money","grana"],["💰 {a} \"emprestou\" grana pra {b}","💵 {a}: toma coins, {b}!"],["💰 {a} contou o cofrinho","💵 {a} rico de mentira"]),
cmd("doce",["sweet"],["🍬 {a} deu doce pra {b}!","🍭 {a}: doce pra {b}"],["🍬 {a} abriu os doces","🍭 {a} pirulito virtual"]),
cmd("elogiar",[],["🌟 {a} elogiou {b}!","👏 {a}: {b}, voce e demais!"],["🌟 {a} elogiou o grupo","👏 {a}: voces sao demais!"]),
cmd("empurrar",[],["🫸 {a} empurrou {b} de leve!","😂 {a} empurrou {b} na fila"],["🫸 {a} empurrou o vento","😂 {a} empurrou a preguica"]),
cmd("escola",["study"],["📚 {a} mandou {b} pra escola!","🎒 {a}: aula, {b}!"],["📚 {a} tocou o sinal","🎒 {a} na aula do chat"]),
cmd("esporte",["sport"],["⚽ {a} convidou {b} pro esporte!","🏀 {a}: bora jogar, {b}?"],["⚽ {a} aquecendo","🏀 {a} treinou sozinho"]),
cmd("estrela",[],["⭐ {a} transformou {b} em estrela!","🌟 {a}: brilha, {b}!"],["⭐ {a} virou estrela do chat","🌟 {a}: brilha!"]),
cmd("fantasma",["ghost"],["👻 {a} assustou {b} de leve!","😈 {a}: buuu, {b}!"],["👻 {a} modo fantasma","😈 {a}: buuu!"]),
cmd("feliz",["happy"],["😄 {a} ficou feliz com {b}!","🥳 {a} compartilhou alegria com {b}"],["😄 {a} esta radiante","🥳 {a} alegria no chat"]),
cmd("festa",["party"],["🎉 {a} convidou {b} pra festa!","🥳 {a}: aparece, {b}!"],["🎉 {a} ligou o som","🥳 {a} festa solo"]),
cmd("flor",["flower"],["🌹 {a} deu uma flor pra {b}!","🌷 {a} presenteou {b} com flores"],["🌹 {a} colheu uma flor","🌷 {a} no jardim"]),
cmd("fogo",["fire"],["🔥 {a} acendeu o clima com {b}!","💥 {a} e {b} energia total"],["🔥 {a} modo fogo","💥 {a} energia total"]),
cmd("foto",["camera"],["📸 {a} tirou foto com {b}!","📷 {a}: sorri, {b}!"],["📸 {a} tirou selfie","📷 {a}: sorri!"]),
cmd("frutas",["fruta"],["🍇 {a} ofereceu frutas pra {b}!","🍌 {a}: toma fruta, {b}"],["🍇 {a} foi a feira","🍌 {a} comeu banana"]),
cmd("funcionario",[],["💼 {a} contratou {b}!","👔 {a}: bem-vindo, {b}"],["💼 {a} abriu vaga","👔 {a} funcionario do mes: eu"]),
cmd("gelo",["ice","frio"],["❄️ {a} congelou {b} 2s!","🧊 {a} jogou neve em {b}"],["❄️ {a} esfriou o chat","🧊 {a} bola de neve"]),
cmd("gosto",[],["💛 {a} disse que gosta de {b}!","😊 {a}: gosto de voce, {b}"],["💛 {a} gosta do fim de semana","😊 {a} modo carinho"]),
cmd("gritar",[],["📢 {a} gritou o nome de {b}!","📣 {a}: OI, {b}!!!"],["📢 {a} gritou pro vazio","📣 {a}: OI, GRUPO!!!"]),
cmd("heroi",["hero"],["🦸 {a} salvou {b} como heroi!","🛡️ {a} deu o manto pra {b}"],["🦸 {a} colocou a capa","🛡️ {a} heroi do dia"]),
cmd("highfive",[],["🙌 {a} deu high-five em {b}!","✋ {a} e {b}: TCHA!"],["🙌 {a} mao no ar","✋ {a}: TCHA no vento"]),
cmd("ignorar",[],["😑 {a} fingiu nao ver {b}","😶 {a} colocou {b} invisivel"],["😑 {a} modo ignore","😶 {a} ignorou notificacoes"]),
cmd("invejar",[],["😒 {a} teve invejinha de {b}","😅 {a}: oxe {b}, que sorte"],["😒 {a} inveja o feriado","😅 {a} inveja quem dorme"]),
cmd("jogo",["game"],["🎮 {a} convidou {b} pra jogar!","🕹️ {a}: 1v1, {b}?"],["🎮 {a} abriu o lobby","🕹️ {a} 1v1 contra o bot"]),
cmd("lua",["moon"],["🌙 {a} olhou a lua com {b}","⭐ {a}: olha a lua, {b}!"],["🌙 {a} saiu ver a lua","⭐ {a}: olha a lua!"]),
cmd("mar",["sea"],["🌊 {a} levou {b} pro mar!","🏄 {a}: bora onda, {b}?"],["🌊 {a} ouviu o mar","🏄 {a} pegou onda solo"]),
cmd("melhoramigo",[],["👬 {a} declarou {b} melhor amigo!","💛 {a}: tu e meu best, {b}"],["👬 {a} bestie do sofa","💛 {a} amizade com a vida"]),
cmd("mentor",[],["📚 {a} virou mentor de {b}!","🧑‍🏫 {a}: aprende comigo, {b}"],["📚 {a} abriu mentoria","🧑‍🏫 {a} sabedoria solo"]),
cmd("musica",["music","som"],["🎵 {a} tocou musica pra {b}!","🎶 {a}: tua soundtrack, {b}"],["🎵 {a} ligou a playlist","🎶 {a} soundtrack do dia"]),
cmd("natureza",["nature"],["🌿 {a} levou {b} pra natureza!","🌳 {a} e {b} no picnic"],["🌿 {a} saiu pro mato","🌳 {a} picnic solo"]),
cmd("ninja",["samurai"],["🥷 {a} ninja apareceu atras de {b}!","⚔️ {a} treinou {b} no caminho ninja"],["🥷 {a} modo ninja","⚔️ {a} treinou o caminho ninja"]),
cmd("noite",["night"],["🌃 {a} desejou boa noite pra {b}","🌙 {a} e {b} de madrugada"],["🌃 {a} olhou o ceu","🌙 {a} quase dormindo"]),
cmd("obrigado",["thanks","valeu"],["🙏 {a} agradeceu {b}!","❤️ {a}: valeu, {b}"],["🙏 {a} espalhou gratidao","❤️ {a}: valeu, vida"]),
cmd("observar",[],["👀 {a} observou {b}...","🔍 {a} analisou {b}"],["👀 {a} observa o grupo","🔍 {a} analisou o chat"]),
cmd("odeio",[],["💢 {a} fingiu odiar {b} (zoeira)!","😤 {a}: te odeio, {b}... mentira kkk"],["💢 {a} modo drama","😤 {a}: odeio segunda kkk"]),
cmd("oi",["ola","hey"],["👋 {a} mandou OI pra {b}!","😊 {a}: olaaa, {b}!"],["👋 {a} gritou OI","😊 {a}: olaaa, pessoal!"]),
cmd("ok",["okay","certo"],["✅ {a} confirmou OK pra {b}","👌 {a}: tudo certo, {b}!"],["✅ {a} de ok com a vida","👌 {a}: tudo certo!"]),
cmd("palhaco",["clown"],["🤡 {a} virou palhaco pra {b} rir!","🎪 {a} montou circo pra {b}"],["🤡 {a} pintou o nariz","🎪 {a} circo solo"]),
cmd("patrao_fun",[],["👔 {a} nomeou {b} patrao!","💼 {a}: manda, {b}!"],["👔 {a} abriu a empresa","💼 {a} patrao de si"]),
cmd("paz",["peace"],["☮️ {a} desejou paz pra {b}","🕊️ {a}: paz, {b}!"],["☮️ {a} modo paz","🕊️ {a}: paz!"]),
cmd("perdoar",[],["💖 {a} perdoou {b}!","🤗 {a}: ta perdoado, {b}"],["💖 {a} modo perdao","🤗 {a}: perdoado, universo"]),
cmd("piscar",[],["😉 {a} piscou pra {b}!","👀 {a}: *pisca* oi, {b}"],["😉 {a} piscou pro nada","👀 {a}: *pisca*"]),
cmd("pizza",["pizzas"],["🍕 {a} ofereceu pizza pra {b}!","🤤 {a}: fatia pra {b}"],["🍕 {a} ligou a pizzaria","🤤 {a} fatia solo"]),
cmd("praia",["beach"],["🏖️ {a} convidou {b} pra praia!","🏝️ {a}: toalha e {b}"],["🏖️ {a} pegou a toalha","🏝️ {a} no solzinho"]),
cmd("proteger",[],["🛡️ {a} protegeu {b}!","🦸 {a}: fica atras de mim, {b}"],["🛡️ {a} modo guarda-costas","🦸 {a} escudo ativado"]),
cmd("provocar",[],["😏 {a} provocou {b} de leve!","😂 {a}: e tu, {b}?"],["😏 {a} provoca o destino","😂 {a} provocacao solo"]),
cmd("puxar",[],["🧲 {a} puxou {b} pra perto!","😄 {a}: vem ca, {b}!"],["🧲 {a} puxou o ar","😄 {a}: vem ca, sofa!"]),
cmd("raiva",["angry"],["😠 {a} fingiu raiva de {b}!","😡 {a}: bravo com {b}... 5s"],["😠 {a} modo novela","😡 {a} raiva da net lenta"]),
cmd("rir",[],["😂 {a} riu muito de {b}!","🤣 {a} caiu na risada com {b}"],["😂 {a} riu sozinho","🤣 {a} ataque de riso"]),
cmd("rival",[],["⚔️ {a} declarou {b} rival!","🔥 {a} vs {b}: rivalidade amigavel"],["⚔️ {a} procura rival","🔥 {a} vs o despertador"]),
cmd("robo",["robot"],["🤖 {a} bipou pra {b}!","⚙️ {a}: beep boop, {b}"],["🤖 {a} reiniciando...","⚙️ {a}: beep boop"]),
cmd("roxo",["purple"],["💜 {a} pintou de roxo com {b}!","🟣 {a} e {b} squad roxo"],["💜 {a} modo roxo","🟣 {a} vibe purple"]),
cmd("salvar",[],["🦸 {a} salvou {b}!","🛡️ {a} chegou a tempo de salvar {b}"],["🦸 {a} de plantao","🛡️ {a} salvou o dia"]),
cmd("socio",[],["🤝 {a} fez sociedade com {b}!","💼 {a} e {b}: socios!"],["🤝 {a} abre sociedade","💼 {a} socio de si"]),
cmd("sol",["sunny"],["☀️ {a} trouxe o sol pra {b}!","🌞 {a}: clareia o dia de {b}"],["☀️ {a} abriu a cortina","🌞 {a} dia de sol"]),
cmd("sono",["dormir","sleep"],["😴 {a} mandou {b} dormir!","💤 {a}: boa noite, {b}"],["😴 {a} bocejou forte!","💤 {a}: boa noite, chat"]),
cmd("sorte",["luck"],["🍀 {a} mandou sorte pra {b}!","✨ {a}: boa sorte, {b}!"],["🍀 {a} pediu sorte","✨ {a}: boa sorte pra mim"]),
cmd("sussurrar",[],["🤫 {a} sussurrou pra {b}","🙊 {a}: psst, {b}..."],["🤫 {a} sussurrou pro vento","🙊 {a}: psst..."]),
cmd("tchau",["bye"],["👋 {a} deu tchau pra {b}!","💙 {a}: ate logo, {b}"],["👋 {a} tchau geral","💙 {a}: ate logo, chat"]),
cmd("trabalho",["work"],["💼 {a} puxou {b} pra trabalhar!","💻 {a}: reuniao, {b}"],["💼 {a} abriu o notebook","💻 {a} no expediente"]),
cmd("triste",["sad"],["😢 {a} ficou triste com {b}","💙 {a}: to aqui, {b}"],["😢 {a} dia cinza","💙 {a} tentou se animar"]),
cmd("viagem",["travel"],["✈️ {a} convidou {b} pra viagem!","🗺️ {a}: faz as malas, {b}!"],["✈️ {a} no aeroporto","🗺️ {a}: faz as malas"]),
cmd("vitoria",["win"],["🏆 {a} comemorou vitoria com {b}!","🥇 {a}: ganhamos, {b}!"],["🏆 {a} comemorou","🥇 {a}: ganhei!"]),
];