function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const t=a[i];a[i]=a[j];a[j]=t;}return a;}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
async function reactSequence(ctx,emojis){const order=shuffle(emojis);for(let i=0;i<order.length;i++){try{await ctx.react(order[i]);}catch(e){}if(i<order.length-1)await sleep(350+Math.floor(Math.random()*250));}}
function makeCmd(name,aliases,emojis,description){return{name,aliases:aliases||[],category:'diversao',description:description||('Reacoes '+name),handler:async(ctx)=>{await reactSequence(ctx,emojis);}};}
module.exports = [
  makeCmd('amor', ["love"], ["❤️","🧡","💛","💚","💙","💜","💕","💖","💗","💘","💝","💋","😘","😍","🥰","🌹","🌸","🌷","💐"], 'Reacoes amor'),
  makeCmd('roxo', ["purple"], ["💜","💙","🖤","🤍","🫦","👄","🦄","🔮","🟣","✨","💫","💎"], 'Reacoes roxo'),
  makeCmd('comida', ["food","comer"], ["🧃","🧋","🍩","🍓","🍕","🍔","🍟","🌮","🍣","🍦","🍰","🍪","🍫","☕","🍺"], 'Reacoes comida'),
  makeCmd('status', ["stat"], ["📜","💛","🈶","🈚","🈵","🆕","🆒","💯","⭐","🔥","⚡","📝"], 'Reacoes status'),
  makeCmd('brabo', ["braba","top"], ["🈹","🈲","✅","🎯","🗽","🔥","💪","😤","😡","💥","👊","🏆","🚀","👑"], 'Reacoes brabo'),
  makeCmd('frutas', ["fruta"], ["🍞","🍇","🍌","🍎","🍊","🍋","🍉","🍒","🍑","🥭","🍍","🥝","🍓"], 'Reacoes frutas'),
  makeCmd('fogo', ["fire"], ["🔥","💥","⚡","🌋","🎆","✨","💫","☄️","🔴"], 'Reacoes fogo'),
  makeCmd('gelo', ["ice","frio"], ["❄️","🧊","🥶","💨","☁️","⛄","💧","🔵"], 'Reacoes gelo'),
  makeCmd('festa', ["party"], ["🎉","🎊","🎈","🎂","🥳","🍾","🥂","🎁","💃","🕺","🎶"], 'Reacoes festa'),
  makeCmd('musica', ["music","som"], ["🎵","🎶","🎤","🎧","🎷","🎸","🎹","🥁","🎺"], 'Reacoes musica'),
  makeCmd('animal', ["bicho","pet"], ["🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐯","🦁","🐸","🦄"], 'Reacoes animal'),
  makeCmd('feliz', ["happy"], ["😀","😃","😄","😁","😆","😂","🤣","😊","😍","🤩","🥳"], 'Reacoes feliz'),
  makeCmd('triste', ["sad"], ["😢","😭","😔","😞","😩","😿","💔","💧"], 'Reacoes triste'),
  makeCmd('raiva', ["angry"], ["😠","😡","🤬","😤","💢","💥","👿","👊"], 'Reacoes raiva'),
  makeCmd('sono', ["dormir","sleep"], ["😴","😪","🥱","💤","🌙","⭐"], 'Reacoes sono'),
  makeCmd('dinheiro', ["money","grana"], ["💰","💵","💴","💶","💸","💳","💎","🤑"], 'Reacoes dinheiro'),
  makeCmd('viagem', ["travel"], ["✈️","🚀","🗺️","🏝️","🏖️","🚗","🚢","🗼"], 'Reacoes viagem'),
  makeCmd('natureza', ["nature"], ["🌲","🌳","🌴","🍀","🌿","🌸","☀️","🌈","🌊"], 'Reacoes natureza'),
  makeCmd('chuva', ["rain"], ["🌧️","⛈️","☔","💧","☁️","🌈"], 'Reacoes chuva'),
  makeCmd('sol', ["sunny"], ["☀️","🌞","🌅","😎","💛","🔥"], 'Reacoes sol'),
  makeCmd('lua', ["moon"], ["🌙","🌕","🌑","⭐","✨","🌌"], 'Reacoes lua'),
  makeCmd('estrela', ["star"], ["⭐","🌟","✨","💫","🌠"], 'Reacoes estrela'),
  makeCmd('coracao', ["heart"], ["❤️","🧡","💛","💚","💙","💜","🖤","🤍","💕","💖"], 'Reacoes coracao'),
  makeCmd('beijo', ["kiss"], ["💋","😘","😚","😙","👄","🫦","❤️"], 'Reacoes beijo'),
  makeCmd('abraco', ["hug"], ["🤗","❤️","💕","🥰","😊","🤝"], 'Reacoes abraco'),
  makeCmd('danca', ["dance"], ["💃","🕺","🎉","🎶","🎵","🥳"], 'Reacoes danca'),
  makeCmd('esporte', ["sport"], ["⚽","🏀","🏈","🎾","🏐","🥊","🏆","🥇"], 'Reacoes esporte'),
  makeCmd('jogo', ["game"], ["🎮","🕹️","🎲","🧩","🎯","🏆","👾"], 'Reacoes jogo'),
  makeCmd('foto', ["camera"], ["📷","📸","📹","🎥","🖼️","🎬"], 'Reacoes foto'),
  makeCmd('escola', ["study"], ["📚","📖","✏️","📝","🎒","🎓"], 'Reacoes escola'),
  makeCmd('trabalho', ["work"], ["💼","💻","📊","📈","📁"], 'Reacoes trabalho'),
  makeCmd('casa', ["home"], ["🏠","🏡","🛋️","🛏️","🔑"], 'Reacoes casa'),
  makeCmd('carro', ["car"], ["🚗","🚕","🚌","🏎️","🚲","🛵"], 'Reacoes carro'),
  makeCmd('aviao', ["plane"], ["✈️","🛫","🛬","🗺️"], 'Reacoes aviao'),
  makeCmd('praia', ["beach"], ["🏖️","🏝️","🌊","☀️","🍹","🕶️"], 'Reacoes praia'),
  makeCmd('noite', ["night"], ["🌃","🌙","⭐","✨","🌌","😴"], 'Reacoes noite'),
  makeCmd('cafe', ["coffee"], ["☕","🍵","🧋","🥐","🍪"], 'Reacoes cafe'),
  makeCmd('doce', ["sweet"], ["🍬","🍭","🍫","🍩","🍪","🧁","🍰","🍦"], 'Reacoes doce'),
  makeCmd('pizza', ["pizzas"], ["🍕","🍔","🍟","🌭","🤤"], 'Reacoes pizza'),
  makeCmd('bebida', ["drink"], ["🧃","🧋","🥤","☕","🍺","🍻","🥂","🍷","🧊"], 'Reacoes bebida'),
  makeCmd('flor', ["flower"], ["🌸","🌹","🥀","🌺","🌻","🌼","🌷","💐"], 'Reacoes flor'),
  makeCmd('mar', ["sea"], ["🌊","🐠","🐟","🐬","🐳","🏄","🏖️"], 'Reacoes mar'),
  makeCmd('fantasma', ["ghost"], ["👻","🎃","💀","☠️","🦇","😈"], 'Reacoes fantasma'),
  makeCmd('robo', ["robot"], ["🤖","👾","💻","⚙️","🚀"], 'Reacoes robo'),
  makeCmd('alien', ["et"], ["👽","👾","🛸","🌌","🚀","🪐"], 'Reacoes alien'),
  makeCmd('palhaco', ["clown"], ["🤡","🎪","🎉","🎈","😂"], 'Reacoes palhaco'),
  makeCmd('rei', ["king","rainha"], ["👑","🦁","🏰","💎","⚔️","🛡️"], 'Reacoes rei'),
  makeCmd('ninja', ["samurai"], ["🥷","⚔️","🗡️","💨","🖤"], 'Reacoes ninja'),
  makeCmd('heroi', ["hero"], ["🦸","💪","🛡️","⚡","🔥","🌟"], 'Reacoes heroi'),
  makeCmd('sorte', ["luck"], ["🍀","🎰","🎲","✨","🌟","💰","🤞"], 'Reacoes sorte'),
  makeCmd('paz', ["peace"], ["☮️","🕊️","🤝","🙏","💚"], 'Reacoes paz'),
  makeCmd('forca', ["power"], ["💪","🦾","⚡","🔥","👊","💥"], 'Reacoes forca'),
  makeCmd('vitoria', ["win"], ["🏆","🥇","🎉","👏","🔥","⭐","👑"], 'Reacoes vitoria'),
  makeCmd('obrigado', ["thanks","valeu"], ["🙏","❤️","😊","🤝","✨"], 'Reacoes obrigado'),
  makeCmd('tchau', ["bye"], ["👋","😊","💙","✈️","🌙"], 'Reacoes tchau'),
  makeCmd('oi', ["ola","hey"], ["👋","😊","🙂","🙌","✨"], 'Reacoes oi'),
  makeCmd('ok', ["okay","certo"], ["✅","👌","👍","😊","💯"], 'Reacoes ok'),
];
