/** Trivia PARTE 3/4 — \~75 perguntas */
module.exports = [
  { q: 'Qual e a capital do Brasil?', opts: ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Belo Horizonte'], correct: [2] },
  { q: 'Em que pais fica a cidade de Nairobi?', opts: ['Uganda', 'Quenia', 'Tanzania', 'Ruanda', 'Etiopia'], correct: [1] },
  { q: 'O pao baguete e tipicamente associado a...?', opts: ['Japao', 'Franca', 'Mexico', 'India', 'Suecia'], correct: [1] },
  { q: 'Qual gas e essencial para a respiracao humana?', opts: ['Nitrogenio so', 'Oxigenio', 'Helio', 'Dioxido de carbono puro', 'Metano'], correct: [1] },
  { q: 'A capital da India e...?', opts: ['Mumbai', 'Nova Deli', 'Calcuta', 'Bangalore', 'Chennai'], correct: [1] },
  { q: 'Qual desporto se joga com um taco e uma bola pequena branca num campo com buracos?', opts: ['Tenis', 'Golfe', 'Basebol so', 'Polo aquatico', 'Andebol'], correct: [1] },
  { q: 'Em que continente fica o Marrocos?', opts: ['Europa', 'Asia', 'Africa', 'Oceania', 'America'], correct: [2] },
  { q: 'O que se usa muitas vezes para adoçar o cha ou o cafe?', opts: ['Sal', 'Acucar', 'Vinagre', 'Pimenta', 'Azeite'], correct: [1] },
  { q: 'Qual pais tem a cidade de Estocolmo?', opts: ['Noruega', 'Suecia', 'Dinamarca', 'Finlandia', 'Islandia'], correct: [1] },
  { q: 'A Lua e um satelite natural da...?', opts: ['Marte', 'Terra', 'Venus', 'Sol direto', 'Jupiter'], correct: [1] },
  { q: 'Qual lingua e oficial em Angola?', opts: ['Frances', 'Portugues', 'Ingles', 'Swahili', 'Arabe'], correct: [1] },
  { q: 'Em muitos restaurantes, a conta pede-se no fim para...?', opts: ['Cantar', 'Pagar a refeicao', 'Trocar de mesa so', 'Desligar a luz'], correct: [1] },
  { q: 'Qual cidade e famosa pelo Cristo Redentor?', opts: ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Lisboa', 'Luanda'], correct: [1] },
  { q: 'O hummus e um pasta tipica do Mediterraneo Oriental feita sobretudo de...?', opts: ['Arroz', 'Grao-de-bico', 'Batata', 'Milho', 'Trigo so'], correct: [1] },
  { q: 'Qual pais tem a forma de ilha grande a sudeste de Africa (no Indico)?', opts: ['Madagascar', 'Islandia', 'Sri Lanka so Asia', 'Cuba', 'Irlanda'], correct: [0] },
  { q: 'Quantos dias tem uma semana comum?', opts: ['5', '6', '7', '8', '10'], correct: [2] },
  { q: 'A capital da Etiopia e...?', opts: ['Lagos', 'Adis Abeba', 'Nairobi', 'Cartum', 'Asmara'], correct: [1] },
  { q: 'Qual instrumento se sopra e e comum em bandas de musica?', opts: ['Violino so cordas', 'Flauta / saxofone (sopro)', 'Bateria so', 'Piano so', 'Harpa'], correct: [1] },
  { q: 'Em que pais fica a cidade de Bangkok?', opts: ['Vietnam', 'Tailandia', 'Cambodja', 'Laos', 'Malasia'], correct: [1] },
  { q: 'O que faz um semaforo vermelho no transito?', opts: ['Acelerar', 'Parar', 'Buzinar so', 'Estacionar obrigatorio'], correct: [1] },
  { q: 'Qual e a capital de Cabo Verde (cidade principal)?', opts: ['Mindelo', 'Praia', 'Sal', 'Assomada', 'Tarrafal'], correct: [1] },
  { q: 'A paella e um prato tipico de...?', opts: ['Alemanha', 'Espanha', 'Polonia', 'Russia', 'Irlanda'], correct: [1] },
  { q: 'Qual planeta e conhecido pelos aneis visiveis?', opts: ['Marte', 'Saturno', 'Mercurio', 'Venus', 'Plutao'], correct: [1] },
  { q: 'Em casa, o micro-ondas serve sobretudo para...?', opts: ['Congelar', 'Aquecer comida', 'Lavar loiça', 'Secar roupa'], correct: [1] },
  { q: 'Qual pais tem a cidade de Jacarta?', opts: ['Filipinas', 'Indonesia', 'Malasia', 'Singapura', 'Brunei'], correct: [1] },
  { q: 'O algodao e muito usado para fazer...?', opts: ['Vidro', 'Roupa / tecidos', 'Metal', 'Pedra', 'Combustivel so'], correct: [1] },
  { q: 'Qual e a capital da Irlanda?', opts: ['Belfast', 'Dublin', 'Cork', 'Galway', 'Limerick'], correct: [1] },
  { q: 'Em que continente fica o Peru?', opts: ['Africa', 'America do Sul', 'Europa', 'Asia', 'Oceania'], correct: [1] },
  { q: 'O miso e um ingrediente fermentado comum na cozinha...?', opts: ['Mexicana', 'Japonesa', 'Italiana', 'Russa', 'Etiope so'], correct: [1] },
  { q: 'Quantas horas tem um dia completo?', opts: ['12', '24', '48', '60', '100'], correct: [1] },
  { q: 'Qual pais tem a cidade de Oslo?', opts: ['Suecia', 'Noruega', 'Dinamarca', 'Finlandia', 'Estonia'], correct: [1] },
  { q: 'A bicicleta move-se principalmente com...?', opts: ['Vela', 'Pedais / forca humana', 'Motor a jato', 'Helice de barco'], correct: [1] },
  { q: 'Qual e a capital de Guine-Bissau?', opts: ['Bissau', 'Conacri', 'Dacar', 'Banjul', 'Freetown'], correct: [0] },
  { q: 'O ceviche e um prato de peixe tipico de varios paises da...?', opts: ['Escandinavia so', 'Costa do Pacifico sul-americano', 'Siberia', 'Antartida'], correct: [1] },
  { q: 'Qual oceano esta no Polo Norte?', opts: ['Pacifico', 'Atlantico', 'Artico', 'Indico', 'Antartico'], correct: [2] },
  { q: 'Em muitos paises, a escola primaria ensina a...?', opts: ['Pilotar avioes', 'Ler e escrever', 'Operar minas', 'Dirigir camioes'], correct: [1] },
  { q: 'Qual pais tem a cidade de Santiago como capital?', opts: ['Argentina', 'Chile', 'Peru', 'Bolivia', 'Uruguai'], correct: [1] },
  { q: 'O falafel e tipicamente feito de...?', opts: ['Carne de vaca so', 'Grao-de-bico / feijao frito', 'So chocolate', 'Peixe cru so'], correct: [1] },
  { q: 'Qual e a capital da Dinamarca?', opts: ['Aarhus', 'Copenhaga', 'Odense', 'Aalborg', 'Roskilde'], correct: [1] },
  { q: 'A neve e agua no estado...?', opts: ['Gasoso so', 'Solido', 'Plasma', 'Liquido quente'], correct: [1] },
  { q: 'Qual pais africano tem Dacar como capital?', opts: ['Mali', 'Senegal', 'Gambia', 'Guine', 'Mauritania'], correct: [1] },
  { q: 'Em smartphones, o WhatsApp serve sobretudo para...?', opts: ['Cozinhar', 'Mensagens e chamadas', 'Lavar o chao', 'Abastecer combustivel'], correct: [1] },
  { q: 'Qual cidade e capital do Japao?', opts: ['Osaka', 'Toquio', 'Quioto', 'Hiroshima', 'Nagoya'], correct: [1] },
  { q: 'O curry e um estilo de tempero/prato muito associado a...?', opts: ['Islandia', 'India e Asia do Sul', 'Patagonia so', 'Alaska'], correct: [1] },
  { q: 'Quantos minutos tem uma hora?', opts: ['30', '60', '100', '24', '12'], correct: [1] },
  { q: 'Qual pais tem a cidade de Viena?', opts: ['Suica', 'Austria', 'Alemanha', 'Hungria', 'Chequia'], correct: [1] },
  { q: 'O azeite e um oleo obtido principalmente de...?', opts: ['Coco so', 'Azeitonas', 'Peixe', 'Milho so', 'Girassol so'], correct: [1] },
  { q: 'Em que continente fica a Nova Zelandia?', opts: ['Europa', 'Asia', 'Oceania', 'Africa', 'America'], correct: [2] },
  { q: 'Qual e a capital de Sao Tome e Principe?', opts: ['Principe', 'Sao Tome', 'Malabo', 'Libreville', 'Douala'], correct: [1] },
  { q: 'O basebol e especialmente popular nos EUA, Japao e...?', opts: ['Mali', 'Coreia / Caribe (entre outros)', 'Finlandia so', 'Nepal so'], correct: [1] },
  { q: 'Qual destes e um estado da materia?', opts: ['Rapido', 'Liquido', 'Colorido', 'Barulhento', 'Doce'], correct: [1] },
  { q: 'A capital da Belgica e...?', opts: ['Antuerpia', 'Bruxelas', 'Bruges', 'Gand', 'Liege'], correct: [1] },
  { q: 'Em muitos lares, o sabao e usado para...?', opts: ['Fritar', 'Limpar / lavar', 'Ligar a TV', 'Abrir portas'], correct: [1] },
  { q: 'Qual pais tem a cidade de Istambul e Ancara como capital?', opts: ['Grecia', 'Turquia', 'Irao', 'Iraque', 'Siria'], correct: [1] },
  { q: 'O tofu e feito a partir de...?', opts: ['Leite de soja', 'Carne de porco', 'Peixe', 'Trigo so pao', 'Ovo so'], correct: [0] },
  { q: 'Qual e a capital da Finlandia?', opts: ['Turku', 'Helsinquia', 'Tampere', 'Oulu', 'Espoo'], correct: [1] },
  { q: 'O Equador e uma linha imaginaria que divide a Terra em...?', opts: ['4 oceanos', 'Hemisferio Norte e Sul', '7 continentes so', '24 fusos fixos'], correct: [1] },
  { q: 'Qual pais tem a cidade de Havana?', opts: ['Mexico', 'Cuba', 'Porto Rico so', 'Haiti', 'Jamaica'], correct: [1] },
  { q: 'Em dias quentes, muita gente bebe...?', opts: ['Agua', 'Areia', 'Oleo de motor', 'Tinta'], correct: [0] },
  { q: 'Qual e a capital da Coreia do Norte?', opts: ['Seul', 'Pyongyang', 'Busan', 'Incheon', 'Daegu'], correct: [1] },
  { q: 'O pão pita e comum em varias cozinhas do...?', opts: ['Artico', 'Mediterraneo / Medio Oriente', 'Amazonia profunda so', 'Antartida'], correct: [1] },
  { q: 'Quantos meses tem um ano comum?', opts: ['10', '11', '12', '13', '24'], correct: [2] },
  { q: 'Qual pais tem a cidade de Zurique?', opts: ['Austria', 'Suica', 'Alemanha', 'Liechtenstein so', 'Franca'], correct: [1] },
  { q: 'A bateria do telemovel guarda...?', opts: ['Agua', 'Energia eletrica', 'Comida', 'Ar comprimido so'], correct: [1] },
  { q: 'Qual e a capital de Timor-Leste?', opts: ['Dili', 'Bali', 'Jacarta', 'Darwin', 'Kupang'], correct: [0] },
  { q: 'O rugby e um desporto de contacto popular na...?', opts: ['Nova Zelandia / Ilhas Britânicas (entre outros)', 'Mongolia so', 'Saara so', 'Siberia so'], correct: [0] },
  { q: 'Qual planeta e o nosso "lar"?', opts: ['Marte', 'Terra', 'Venus', 'Jupiter', 'Saturno'], correct: [1] },
  { q: 'A capital da Hungria e...?', opts: ['Debrecen', 'Budapeste', 'Pecs', 'Szeged', 'Miskolc'], correct: [1] },
  { q: 'Em supermercados, a secao de frios costuma ter...?', opts: ['Martelos', 'Queijos e fiambres', 'Plantas de jardim', 'Pneus'], correct: [1] },
  { q: 'Qual pais tem a cidade de Lagos e Abuja como capital?', opts: ['Gana', 'Nigeria', 'Camaroes', 'Benim', 'Togo'], correct: [1] },
  { q: 'O wasabi e um condimento picante associado a...?', opts: ['Mexico', 'Japao', 'Italia', 'Russia', 'Etiopia'], correct: [1] },
  { q: 'Qual e a capital da Republica Checa?', opts: ['Brno', 'Praga', 'Ostrava', 'Plzen', 'Liberec'], correct: [1] },
  { q: 'O GPS no telemovel ajuda a...?', opts: ['Cozinhar arroz', 'Navegar / localizar', 'Lavar o carro', 'Cortar cabelo'], correct: [1] },
  { q: 'Qual pais tem a cidade de Beirute?', opts: ['Siria', 'Libano', 'Jordania', 'Iraque', 'Israel'], correct: [1] },
  { q: 'A melancia e tipicamente...?', opts: ['Salteada com sal so', 'Fruta refrescante', 'Um tipo de peixe', 'Um cereal'], correct: [1] },
  { q: 'Qual e a capital da Escocia (no Reino Unido)?', opts: ['Glasgow', 'Edimburgo', 'Aberdeen', 'Dundee', 'Inverness'], correct: [1] },
  { q: 'Em muitos paises, o domingo e dia de...?', opts: ['So trabalho obrigatorio', 'Descanso / fim de semana (comum)', 'So eleicoes', 'So exame nacional'], correct: [1] }
];
