/** Trivia PARTE 2/4 — \~75 perguntas */
module.exports = [
  { q: 'Qual e a capital da Alemanha?', opts: ['Munique', 'Hamburgo', 'Berlim', 'Frankfurt', 'Colonia'], correct: [2] },
  { q: 'Em que pais fica a cidade de Istambul?', opts: ['Grecia', 'Turquia', 'Bulgaria', 'Siria', 'Irao'], correct: [1] },
  { q: 'O futebol americano e especialmente popular nos...?', opts: ['EUA', 'Brasil', 'Japao', 'Nigeria', 'Suecia'], correct: [0] },
  { q: 'Qual lingua se fala oficialmente na Alemanha?', opts: ['Holandes', 'Alemao', 'Dinamarques', 'Polaco', 'Frances'], correct: [1] },
  { q: 'A Grande Mesquita de Meca fica em que pais?', opts: ['Iraque', 'Arabia Saudita', 'Egito', 'Turquia', 'Marrocos'], correct: [1] },
  { q: 'Qual destes e um cereal base em muitos pequenos-almocos?', opts: ['Arroz doce so', 'Aveia', 'Sal', 'Vinagre', 'Pimenta'], correct: [1] },
  { q: 'Onde fica a Estátua da Liberdade?', opts: ['Paris', 'Nova Iorque', 'Londres', 'Roma', 'Toronto'], correct: [1] },
  { q: 'Qual pais e famoso pelo sushi?', opts: ['China', 'Japao', 'Tailandia', 'Vietnam', 'Coreia so'], correct: [1] },
  { q: 'A capital da Espanha e...?', opts: ['Barcelona', 'Madrid', 'Sevilha', 'Valencia', 'Lisboa'], correct: [1] },
  { q: 'Qual oceano banha a costa oeste dos EUA?', opts: ['Atlantico', 'Pacifico', 'Indico', 'Artico'], correct: [1] },
  { q: 'Em muitos paises, o dia 1 de janeiro e...?', opts: ['Natal', 'Ano Novo', 'Pascoa', 'Halloween'], correct: [1] },
  { q: 'Qual animal produz a maior parte do leite consumido no mundo?', opts: ['Cabra', 'Vaca', 'Camelo', 'Ovelha', 'Bufalo so'], correct: [1] },
  { q: 'O Nilo atravessa principalmente o continente...?', opts: ['Asia', 'Africa', 'Europa', 'America'], correct: [1] },
  { q: 'Qual pais tem a bandeira com uma folha de bordo?', opts: ['EUA', 'Canada', 'Mexico', 'Reino Unido', 'Australia'], correct: [1] },
  { q: 'A lingua oficial da Franca e...?', opts: ['Ingles', 'Frances', 'Alemao', 'Italiano', 'Espanhol'], correct: [1] },
  { q: 'Qual destes e um legume de raiz laranja?', opts: ['Batata', 'Cenoura', 'Alface', 'Tomate', 'Pepino'], correct: [1] },
  { q: 'Onde se situa a cidade de Lagos (grande metropole)?', opts: ['Gana', 'Nigeria', 'Quenia', 'Egipto', 'Marrocos'], correct: [1] },
  { q: 'Qual instrumento tem 88 teclas no modelo padrao de piano?', opts: ['Violino', 'Piano', 'Flauta', 'Trompete', 'Bateria'], correct: [1] },
  { q: 'A capital da Italia e...?', opts: ['Milao', 'Napoles', 'Roma', 'Turim', 'Veneza'], correct: [2] },
  { q: 'Em que continente fica a Argentina?', opts: ['Europa', 'Africa', 'America do Sul', 'Asia', 'Oceania'], correct: [2] },
  { q: 'O cha preto com leite e muito associado ao...?', opts: ['Reino Unido', 'Mexico', 'Islandia so', 'Mali'], correct: [0] },
  { q: 'Qual gas os seres humanos expiram em maior proporcao no ar expirado (vs inspirado)?', opts: ['Oxigenio puro', 'Dioxido de carbono (mais que o inspirado)', 'Helio', 'Ozono'], correct: [1] },
  { q: 'A cidade de Pequim e capital de...?', opts: ['Japao', 'China', 'Coreia do Sul', 'Mongolia', 'Taiwan'], correct: [1] },
  { q: 'Qual desporto usa uma rede e uma bola amarela pequena?', opts: ['Golfe', 'Tenis', 'Rugby', 'Boxe', 'Natacao'], correct: [1] },
  { q: 'O Amazonas corre sobretudo por qual grande pais?', opts: ['Chile', 'Brasil', 'Uruguai', 'Portugal', 'Africa do Sul'], correct: [1] },
  { q: 'Qual e um cumprimento em japones para "bom dia"?', opts: ['Konbanwa', 'Ohayou', 'Sayonara', 'Arigato', 'Sumimasen'], correct: [1] },
  { q: 'A capital do Reino Unido e...?', opts: ['Manchester', 'Londres', 'Edimburgo so', 'Dublin', 'Cardiff'], correct: [1] },
  { q: 'Qual fruta e amarela por fora e branca por dentro quando madura (comum)?', opts: ['Maca vermelha', 'Banana', 'Uva roxa', 'Ameixa'], correct: [1] },
  { q: 'Em que pais fica o Machu Picchu?', opts: ['Mexico', 'Peru', 'Bolivia', 'Chile', 'Colombia'], correct: [1] },
  { q: 'O hino nacional costuma tocar antes de muitos jogos de...?', opts: ['So xadrez', 'Futebol e outros desportos', 'So videojogos', 'So cartas'], correct: [1] },
  { q: 'Qual pais africano tem Cairo como capital?', opts: ['Sudao', 'Egito', 'Libia', 'Argelia', 'Tunisia'], correct: [1] },
  { q: 'A pizza e normalmente feita com que base?', opts: ['Arroz', 'Massa de farinha', 'So peixe', 'Chocolate'], correct: [1] },
  { q: 'Qual destes e um pais da America Central?', opts: ['Canada', 'Costa Rica', 'Chile', 'Noruega', 'Australia'], correct: [1] },
  { q: 'O Sol e uma...?', opts: ['Planeta', 'Estrela', 'Lua', 'Cometa', 'Galaxia inteira'], correct: [1] },
  { q: 'Qual cidade e famosa pelo Big Ben?', opts: ['Paris', 'Londres', 'Berlim', 'Roma', 'Amesterdao'], correct: [1] },
  { q: 'Em muitos supermercados, o pao fica na secao de...?', opts: ['Congelados so', 'Padaria', 'Ferragens', 'Jardim'], correct: [1] },
  { q: 'A capital de Angola e...?', opts: ['Lobito', 'Luanda', 'Huambo', 'Benguela', 'Maputo'], correct: [1] },
  { q: 'Qual lingua se escreve muitas vezes da direita para a esquerda?', opts: ['Ingles', 'Arabe', 'Portugues', 'Frances', 'Sueco'], correct: [1] },
  { q: 'O que e o Himalaia?', opts: ['Um oceano', 'Uma cadeia de montanhas', 'Um deserto de areia so', 'Uma cidade'], correct: [1] },
  { q: 'Qual pais e famoso pelo tango?', opts: ['Brasil', 'Argentina', 'Mexico', 'Portugal', 'Franca'], correct: [1] },
  { q: 'Em casa, o frigorifico serve principalmente para...?', opts: ['Cozinhar', 'Conservar alimentos a frio', 'Lavar roupa', 'Aquecer agua'], correct: [1] },
  { q: 'Qual e a capital do Mexico?', opts: ['Guadalajara', 'Cidade do Mexico', 'Cancun', 'Monterrey', 'Tijuana'], correct: [1] },
  { q: 'O críquete e muito popular na India e no...?', opts: ['Islandia', 'Reino Unido / Commonwealth', 'Mali', 'Chile so'], correct: [1] },
  { q: 'Qual destes animais e um mamifero?', opts: ['Tubarao', 'Golfinho', 'Sardinha', 'Polvo', 'Caranguejo'], correct: [1] },
  { q: 'A Torre de Pisa inclina-se em que pais?', opts: ['Franca', 'Italia', 'Espanha', 'Grecia', 'Turquia'], correct: [1] },
  { q: 'Qual refeicao muita gente faz a meio da manha?', opts: ['Jantar formal', 'Lanche / snack', 'Ceia de Natal so', 'Brunch obrigatorio'], correct: [1] },
  { q: 'Em que continente fica a Suecia?', opts: ['Asia', 'Europa', 'Africa', 'Oceania', 'America'], correct: [1] },
  { q: 'O kimchi e um prato fermentado tipico da...?', opts: ['Italia', 'Coreia', 'Mexico', 'Mali', 'Finlandia'], correct: [1] },
  { q: 'Qual pais tem forma longa e estreita na costa oeste da America do Sul?', opts: ['Brasil', 'Chile', 'Uruguai', 'Equador', 'Paraguai'], correct: [1] },
  { q: 'A agua ferve a cerca de quantos graus Celsius (ao nivel do mar)?', opts: ['50', '100', '0', '37', '200'], correct: [1] },
  { q: 'Qual e um meio de transporte publico comum em grandes cidades?', opts: ['Submarino pessoal', 'Metro / autocarro', 'Foguetao', 'Trator so agricola'], correct: [1] },
  { q: 'A capital da Russia e...?', opts: ['S. Petersburgo', 'Moscovo', 'Kiev', 'Minsk', 'Baku'], correct: [1] },
  { q: 'Qual fruta ciclica e vermelha por fora, comum em sobremesas?', opts: ['Banana', 'Morango', 'Abacate', 'Melancia so verde'], correct: [1] },
  { q: 'Onde fica o Coliseu antigo famoso?', opts: ['Atenas', 'Roma', 'Cairo', 'Istambul', 'Paris'], correct: [1] },
  { q: 'Em muitos paises, se usa o cinto de seguranca no...?', opts: ['Quarto', 'Carro', 'Chuveiro', 'Elevador so'], correct: [1] },
  { q: 'Qual pais africano tem Accra como capital?', opts: ['Nigeria', 'Gana', 'Togo', 'Benim', 'Costa do Marfim'], correct: [1] },
  { q: 'O saque e uma bebida alcoolica tradicional ligada ao...?', opts: ['Mexico', 'Japao', 'Alemanha', 'Brasil', 'Escocia so'], correct: [1] },
  { q: 'Qual planeta e o mais proximo do Sol?', opts: ['Venus', 'Mercurio', 'Terra', 'Marte', 'Neptuno'], correct: [1] },
  { q: 'A capital da Polonia e...?', opts: ['Cracovia', 'Varsovia', 'Gdansk', 'Wroclaw', 'Lodz'], correct: [1] },
  { q: 'Qual destes e tipicamente um doce de chocolate?', opts: ['Salada', 'Bolo de chocolate', 'Sopa de peixe', 'Arroz branco so'], correct: [1] },
  { q: 'Em que pais fica a cidade de Toronto?', opts: ['EUA', 'Canada', 'Reino Unido', 'Australia', 'Nova Zelandia'], correct: [1] },
  { q: 'O yoga tem origens historicas fortes na...?', opts: ['Escandinavia', 'India', 'Amazonia', 'Antartida'], correct: [1] },
  { q: 'Qual destes e um pais insular no Caribe?', opts: ['Bolivia', 'Jamaica', 'Paraguai', 'Suica', 'Mongolia'], correct: [1] },
  { q: 'Quando chove, muita gente usa...?', opts: ['Oculos de sol so', 'Guarda-chuva', 'Chinelo de neve', 'Mochila de praia so'], correct: [1] },
  { q: 'A capital da Grecia e...?', opts: ['Esparta', 'Atenas', 'Salonica', 'Creta', 'Rodes'], correct: [1] },
  { q: 'Qual metal e usado em muitos fios eletricos?', opts: ['Madeira', 'Cobre', 'Algodao', 'Vidro', 'Borracha so'], correct: [1] },
  { q: 'O reggae tem raizes fortes na...?', opts: ['Jamaica', 'Finlandia', 'Mongolia', 'Suica', 'Nepal'], correct: [0] },
  { q: 'Qual pais tem Seul como capital?', opts: ['Coreia do Norte', 'Coreia do Sul', 'Japao', 'China', 'Vietnam'], correct: [1] },
  { q: 'Em casa, a lavadora serve para...?', opts: ['Fritar', 'Lavar roupa', 'Assar pao', 'Cortar relva'], correct: [1] },
  { q: 'Qual deserto e famoso no norte de Africa?', opts: ['Gobi', 'Saara', 'Atacama', 'Kalahari so sul', 'Antartico'], correct: [1] },
  { q: 'A lingua oficial de Cabo Verde e...?', opts: ['Frances', 'Portugues', 'Ingles', 'Arabe', 'Swahili'], correct: [1] },
  { q: 'Qual cidade italiana e famosa pelos canais?', opts: ['Roma', 'Veneza', 'Milao', 'Napoles', 'Turim'], correct: [1] },
  { q: 'O que muita gente faz antes de dormir?', opts: ['Escovar os dentes', 'Correr uma maratona', 'Pintar a casa', 'Viajar de aviao'], correct: [0] },
  { q: 'Qual pais tem a cidade de Casablanca?', opts: ['Argelia', 'Marrocos', 'Tunisia', 'Libia', 'Egito'], correct: [1] },
  { q: 'A banana e, botanicamente, muitas vezes classificada como...?', opts: ['Mineral', 'Fruta (baga na pratica botânica)', 'Carne', 'Cereal so'], correct: [1] },
  { q: 'Qual continente e o mais frio em media?', opts: ['Africa', 'Antartida', 'America do Sul', 'Europa'], correct: [1] },
  { q: 'Em que pais se fala oficialmente o finlandês?', opts: ['Suecia so', 'Finlandia', 'Noruega so', 'Dinamarca'], correct: [1] },
  { q: 'O metro (unidade) mede...?', opts: ['Peso', 'Comprimento', 'Temperatura', 'Tempo', 'Som'], correct: [1] }
];
