/** Trivia PARTE 1/4 — \~75 perguntas */
module.exports = [
  { q: 'Qual e o unico pais com capital em dois continentes?', opts: ['Russia', 'Turquia', 'Egito', 'Cazaquistao', 'Panama'], correct: [1] },
  { q: 'Em que ano caiu o Muro de Berlim?', opts: ['1987', '1989', '1991', '1985', '1990'], correct: [1] },
  { q: 'Qual e o maior oceano do planeta?', opts: ['Atlantico', 'Indico', 'Pacifico', 'Artico', 'Antartico'], correct: [2] },
  { q: 'Quem escreveu Dom Quixote?', opts: ['Shakespeare', 'Camoes', 'Cervantes', 'Dante', 'Tolstoi'], correct: [2] },
  { q: 'O simbolo quimico Au corresponde a...?', opts: ['Prata', 'Aluminio', 'Ouro', 'Argonio', 'Uranio'], correct: [2] },
  { q: 'Qual pais tem mais fusos horarios (com territorios)?', opts: ['Russia', 'EUA', 'Franca', 'China', 'Brasil'], correct: [2] },
  { q: 'A Grande Muralha e associada a qual pais?', opts: ['Japao', 'Coreia', 'China', 'Mongolia', 'India'], correct: [2] },
  { q: 'Qual planeta e o "Planeta Vermelho"?', opts: ['Venus', 'Jupiter', 'Marte', 'Mercurio', 'Saturno'], correct: [2] },
  { q: 'Lingua oficial mais falada no Brasil?', opts: ['Espanhol', 'Portugues', 'Ingles', 'Frances', 'Guarani'], correct: [1] },
  { q: 'Onde fica o deserto do Saara?', opts: ['Asia', 'America do Sul', 'Africa', 'Australia', 'Europa'], correct: [2] },
  { q: 'Moeda do Japao?', opts: ['Yuan', 'Won', 'Iene', 'Baht', 'Dolar'], correct: [2] },
  { q: 'Quem pintou a Mona Lisa?', opts: ['Michelangelo', 'Van Gogh', 'Leonardo da Vinci', 'Picasso', 'Rembrandt'], correct: [2] },
  { q: 'Rio frequentemente citado como o mais longo do mundo?', opts: ['Amazonas', 'Nilo', 'Yangtze', 'Mississipi', 'Congo'], correct: [0, 1] },
  { q: 'Em que continente fica o Egito?', opts: ['Asia', 'Europa', 'Africa', 'Oceania', 'America'], correct: [2] },
  { q: 'Quem sediou a Copa do Mundo de 2010?', opts: ['Brasil', 'Alemanha', 'Africa do Sul', 'Espanha', 'Qatar'], correct: [2] },
  { q: 'No Japao, ao entrar em casa e comum tirar...?', opts: ['O chapeu', 'Os sapatos', 'O relogio', 'A carteira'], correct: [1] },
  { q: 'Pequeno-almoco em PT/BR e o que muitos chamam de...?', opts: ['Lunch', 'Breakfast', 'Dinner', 'Supper'], correct: [1] },
  { q: 'Comida tipicamente associada a Italia?', opts: ['Sushi', 'Tacos', 'Pizza', 'Pad Thai', 'Kimchi'], correct: [2] },
  { q: 'Pao chato de tandoor muito comum na India?', opts: ['Baguete', 'Naan', 'Pretzel', 'Ciabatta'], correct: [1] },
  { q: 'Moeda oficial de Mocambique?', opts: ['Rand', 'Kwanza', 'Metical', 'Xelim', 'Euro'], correct: [2] },
  { q: 'Bebida cultural forte na Argentina/Uruguai?', opts: ['Cafe expresso', 'Mate / chimarrao', 'Cha preto', 'Kombucha'], correct: [1] },
  { q: 'Transporte icone de Londres?', opts: ['Gondola', 'Double-decker', 'Tuk-tuk', 'Maglev', 'Riquixa'], correct: [1] },
  { q: 'Fufu, em varias regioes da Africa Ocidental, e...?', opts: ['Uma danca', 'Uma comida de base', 'Um instrumento', 'Uma lingua'], correct: [1] },
  { q: 'Pais do Carnaval do Rio?', opts: ['Argentina', 'Brasil', 'Mexico', 'Colombia', 'Portugal'], correct: [1] },
  { q: 'Festival da Primavera na China e tambem chamado...?', opts: ['Thanksgiving', 'Ano Novo Chines', 'Halloween', 'Pascoa'], correct: [1] },
  { q: 'Cumprimento tipico em espanhol?', opts: ['Bonjour', 'Hola', 'Ciao', 'Ni hao', 'Salam'], correct: [1] },
  { q: 'Prato coreano de arroz com vegetais e carne?', opts: ['Sushi', 'Bibimbap', 'Pad thai', 'Paella'], correct: [1] },
  { q: 'Cumprimento comum em muitos paises arabes?', opts: ['Namaste', 'As-salamu alaykum', 'Konnichiwa', 'Guten Tag'], correct: [1] },
  { q: 'Dia dos Mortos no Mexico?', opts: ['Halloween so', 'Dia de Muertos', 'Thanksgiving', 'Carnaval'], correct: [1] },
  { q: 'Continente com mais paises?', opts: ['Asia', 'Europa', 'Africa', 'America', 'Oceania'], correct: [2] },
  { q: 'Capital da Australia?', opts: ['Sydney', 'Melbourne', 'Canberra', 'Perth', 'Brisbane'], correct: [2] },
  { q: 'No Brasil, o telemovel costuma chamar-se...?', opts: ['Celular', 'Handy', 'Mobile', 'Handphone'], correct: [0] },
  { q: 'Desporto mais popular na America do Sul?', opts: ['Cricket', 'Futebol', 'Basebol', 'Rugby'], correct: [1] },
  { q: 'Cha tipico de Marrocos?', opts: ['Cha preto com leite', 'Cha de menta', 'Matcha', 'Cha gelado'], correct: [1] },
  { q: 'Pais das tulipas e de Amesterdao?', opts: ['Belgica', 'Paises Baixos', 'Dinamarca', 'Suecia'], correct: [1] },
  { q: 'Safari classico de vida selvagem e tipico de...?', opts: ['Quenia/Tanzania', 'Islandia', 'Finlandia', 'Nepal so'], correct: [0] },
  { q: 'Pastel de nata e historicamente ligado a...?', opts: ['Porto', 'Lisboa (Belem)', 'Faro', 'Coimbra'], correct: [1] },
  { q: 'Oceano na costa leste de Mocambique?', opts: ['Pacifico', 'Atlantico', 'Indico', 'Artico'], correct: [2] },
  { q: 'Prato tradicional mocambicano?', opts: ['Sushi', 'Matapa', 'Paella', 'Poutine'], correct: [1] },
  { q: 'Canada fica em que continente?', opts: ['Europa', 'Asia', 'America do Norte', 'Oceania'], correct: [2] },
  { q: 'Qual NAO tem portugues como lingua oficial?', opts: ['Angola', 'Mocambique', 'Cabo Verde', 'Senegal', 'Guine-Bissau'], correct: [3] },
  { q: 'Montanha mais alta do mundo acima do nivel do mar?', opts: ['K2', 'Everest', 'Kilimanjaro', 'Mont Blanc', 'Aconcagua'], correct: [1] },
  { q: 'Quem foi o primeiro homem na Lua?', opts: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], correct: [1] },
  { q: 'Capital da Franca?', opts: ['Lyon', 'Marselha', 'Paris', 'Nice', 'Bordeaux'], correct: [2] },
  { q: 'Quantos continentes se costumam contar no modelo escolar comum?', opts: ['5', '6', '7', '4', '8'], correct: [1, 2] },
  { q: 'Instrumento de cordas tipico do fado portugues?', opts: ['Shamisen', 'Guitarra portuguesa', 'Sitar', 'Balalaica'], correct: [1] },
  { q: 'Qual pais e uma ilha e tambem um continente?', opts: ['Madagascar', 'Australia', 'Gra-Bretanha', 'Groenlandia'], correct: [1] },
  { q: 'A pizza Margherita surgiu em que pais?', opts: ['Franca', 'Italia', 'Grecia', 'Espanha'], correct: [1] },
  { q: 'Qual e a capital de Mocambique?', opts: ['Beira', 'Nampula', 'Maputo', 'Pemba', 'Quelimane'], correct: [2] },
  { q: 'O Taj Mahal fica em que pais?', opts: ['Paquistao', 'India', 'Bangladesh', 'Nepal', 'Irao'], correct: [1] },
  { q: 'Qual animal e simbolo da Australia?', opts: ['Panda', 'Canguru', 'Urso polar', 'Lhama', 'Tigre'], correct: [1] },
  { q: 'Em que pais se fala principalmente holandes (neerlandes)?', opts: ['Alemanha', 'Paises Baixos', 'Dinamarca', 'Polonia'], correct: [1] },
  { q: 'O canal do Suez liga o Mediterraneo a...?', opts: ['Atlantico', 'Mar Vermelho', 'Mar Negro', 'Pacifico'], correct: [1] },
  { q: 'Qual vitamina o sol ajuda o corpo a produzir?', opts: ['Vitamina C', 'Vitamina D', 'Vitamina B12', 'Vitamina A'], correct: [1] },
  { q: 'H2O e a formula da...?', opts: ['Sal', 'Agua', 'Oxigenio', 'Gas carbonico', 'Ozono'], correct: [1] },
  { q: 'Qual pais tem a forma de uma bota no mapa?', opts: ['Grecia', 'Italia', 'Portugal', 'Chile', 'Vietname'], correct: [1] },
  { q: 'O samba tem raizes fortes em que pais?', opts: ['Argentina', 'Brasil', 'Cuba so', 'Espanha'], correct: [1] },
  { q: 'Qual cidade e famosa pela Torre Eiffel?', opts: ['Roma', 'Paris', 'Londres', 'Berlim', 'Madrid'], correct: [1] },
  { q: 'Em muitos paises, se diz "obrigado". Em frances?', opts: ['Gracias', 'Merci', 'Danke', 'Arigato', 'Spasibo'], correct: [1] },
  { q: 'Qual destes e um pais nordico?', opts: ['Espanha', 'Suecia', 'Grecia', 'Turquia', 'Marrocos'], correct: [1] },
  { q: 'O cafe espresso tem origem cultural forte em...?', opts: ['Brasil so', 'Italia', 'China', 'Russia'], correct: [1] },
  { q: 'Qual oceano fica entre Africa e Australia?', opts: ['Atlantico', 'Pacifico', 'Indico', 'Artico'], correct: [2] },
  { q: 'A lingua swahili e muito falada em partes de...?', opts: ['Africa Oriental', 'Europa do Norte', 'America do Sul', 'Siberia'], correct: [0] },
  { q: 'Qual pais e famoso pelo chocolate e pelos Alpes?', opts: ['Belgica so', 'Suica', 'Austria so', 'Polonia'], correct: [1] },
  { q: 'O que se come muitas vezes com pauzinhos na Asia Oriental?', opts: ['So sopa de colher', 'Arroz e outros pratos', 'So pao', 'So carne crua'], correct: [1] },
  { q: 'Capital da Africa do Sul administrativa (uma das)?', opts: ['Joanesburgo', 'Pretoria', 'Durban', 'Cidade do Cabo e tambem legislativa'], correct: [1, 3] },
  { q: 'Qual invento e atribuido a Alexander Graham Bell (classico)?', opts: ['Lampada', 'Telefone', 'Aviao', 'Imprensa'], correct: [1] },
  { q: 'O deserto de Atacama fica principalmente no...?', opts: ['Chile', 'Egito', 'Australia', 'China', 'Mali'], correct: [0] },
  { q: 'Em ingles, "thank you" significa...?', opts: ['Adeus', 'Obrigado', 'Por favor', 'Desculpa'], correct: [1] },
  { q: 'Qual pais africano tem portugues como lingua oficial e Maputo como capital?', opts: ['Angola', 'Mocambique', 'Guine Equatorial', 'Senegal'], correct: [1] },
  { q: 'A muralha de coral da Great Barrier Reef fica perto de...?', opts: ['Brasil', 'Australia', 'India', 'Mexico'], correct: [1] },
  { q: 'Qual bebida e feita de uvas fermentadas?', opts: ['Cerveja', 'Vinho', 'Saque so arroz', 'Whisky so', 'Cha'], correct: [1] },
  { q: 'O Kilimanjaro fica em que pais?', opts: ['Quenia so', 'Tanzania', 'Etiopia', 'Uganda'], correct: [1] },
  { q: 'Qual e a capital de Portugal?', opts: ['Porto', 'Lisboa', 'Coimbra', 'Faro', 'Braga'], correct: [1] },
  { q: 'Em que pais fica a cidade de Dubai?', opts: ['Arabia Saudita', 'Emirados Arabes Unidos', 'Qatar', 'Oma'], correct: [1] },
  { q: 'O arroz e alimento base em grande parte de...?', opts: ['So Europa', 'Asia', 'So Artico', 'Antartida'], correct: [1] }
];
