/** Trivia PARTE 4/4 — \~75 perguntas */
module.exports = [
  { q: 'Qual e a capital da Argentina?', opts: ['Cordoba', 'Buenos Aires', 'Rosario', 'Mendoza', 'La Plata'], correct: [1] },
  { q: 'Em que pais fica a cidade de Addis Abeba?', opts: ['Quenia', 'Etiopia', 'Sudao', 'Somalia', 'Eritreia'], correct: [1] },
  { q: 'O chocolate e feito principalmente a partir de...?', opts: ['Cafe', 'Cacau', 'Cha', 'Arroz', 'Milho'], correct: [1] },
  { q: 'Qual e o maior mamifero do planeta?', opts: ['Elefante africano', 'Baleia-azul', 'Girafa', 'Urso polar', 'Hipopotamo'], correct: [1] },
  { q: 'A capital de Israel (reconhecida por muitos paises) e...?', opts: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Eilat', 'Nazare'], correct: [1] },
  { q: 'Em que continente fica a Indonesia (em grande parte)?', opts: ['Europa', 'Asia / Oceania (arquipelago)', 'Africa', 'America'], correct: [1] },
  { q: 'O que se usa para medir a temperatura do corpo?', opts: ['Martelo', 'Termometro', 'Compasso', 'Balanca so', 'Metro'], correct: [1] },
  { q: 'Qual pais tem a cidade de Manila?', opts: ['Indonesia', 'Filipinas', 'Vietnam', 'Tailandia', 'Malasia'], correct: [1] },
  { q: 'A cerveja e tradicionalmente feita com...?', opts: ['So leite', 'Cereais / malte e agua', 'So vinho', 'So cha', 'So sumo'], correct: [1] },
  { q: 'Qual e a capital da Colombia?', opts: ['Medellin', 'Bogota', 'Cali', 'Cartagena', 'Barranquilla'], correct: [1] },
  { q: 'O Sahara cobre grande parte do norte de...?', opts: ['Europa', 'Africa', 'Australia', 'Canada', 'India'], correct: [1] },
  { q: 'Em aeroportos, o passaporte serve para...?', opts: ['Pagar o cafe so', 'Identificacao em viagens internacionais', 'Abrir malas', 'Dirigir so'], correct: [1] },
  { q: 'Qual pais tem a cidade de Varsovia?', opts: ['Ucrania', 'Polonia', 'Chequia', 'Eslovaquia', 'Lituania'], correct: [1] },
  { q: 'O abacate e uma fruta comum em saladas e no...?', opts: ['Gelo seco', 'Guacamole', 'Sopa de gelo', 'Cha preto so'], correct: [1] },
  { q: 'Qual e a capital da Ucrania?', opts: ['Odessa', 'Kiev', 'Lviv', 'Kharkiv', 'Dnipro'], correct: [1] },
  { q: 'A fotossintese nas plantas usa sobretudo a luz do...?', opts: ['Lua so', 'Sol', 'Fogo de vela so', 'Telemovel'], correct: [1] },
  { q: 'Qual pais tem a cidade de Riad?', opts: ['Iraque', 'Arabia Saudita', 'Kuwait', 'Catar', 'Barein'], correct: [1] },
  { q: 'Em muitos paises, a nota de 100 e um tipo de...?', opts: ['Fruta', 'Dinheiro / nota', 'Ferramenta', 'Animal'], correct: [1] },
  { q: 'Qual e a capital da Romania?', opts: ['Cluj', 'Bucareste', 'Timisoara', 'Iasi', 'Constanta'], correct: [1] },
  { q: 'O sushi tradicional inclui muitas vezes peixe e...?', opts: ['Batata frita so', 'Arroz', 'Pao de forma', 'Massa de lasanha'], correct: [1] },
  { q: 'Em que continente fica o Senegal?', opts: ['Asia', 'Africa', 'Europa', 'Oceania', 'America'], correct: [1] },
  { q: 'Qual aparelho mostra horas no pulso?', opts: ['Relogio', 'Garfo', 'Chave de fendas', 'Caneta so'], correct: [0] },
  { q: 'A capital da Noruega e...?', opts: ['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Tromso'], correct: [1] },
  { q: 'O milho e um cereal importante na cozinha de...?', opts: ['So Islandia', 'Mexico e Americas (entre outros)', 'So Antartida', 'So Himalaia'], correct: [1] },
  { q: 'Qual pais tem a cidade de Caracas?', opts: ['Colombia', 'Venezuela', 'Equador', 'Peru', 'Panama'], correct: [1] },
  { q: 'A Terra demora cerca de quantos dias a dar a volta ao Sol?', opts: ['30', '365', '7', '24', '100'], correct: [1] },
  { q: 'Qual e a capital de Bangladesh?', opts: ['Chittagong', 'Daca', 'Khulna', 'Sylhet', 'Rajshahi'], correct: [1] },
  { q: 'Em dias de frio, muita gente usa...?', opts: ['Casaco', 'Fato de banho so', 'Chinelo de praia so', 'Oculos de sol so'], correct: [0] },
  { q: 'Qual pais tem a cidade de Atenas?', opts: ['Italia', 'Grecia', 'Turquia', 'Albania', 'Bulgaria'], correct: [1] },
  { q: 'O queijo e tipicamente feito a partir de...?', opts: ['Agua do mar', 'Leite', 'Sumo de limao so', 'Farinha so'], correct: [1] },
  { q: 'Qual e a capital do Vietname?', opts: ['Ho Chi Minh', 'Hanoi', 'Da Nang', 'Hue', 'Hai Phong'], correct: [1] },
  { q: 'O futebol se joga com quantos jogadores por equipa em campo (oficial 11)?', opts: ['5', '7', '11', '15', '22 em cada lado'], correct: [2] },
  { q: 'Em que continente fica o Canada?', opts: ['Europa', 'America do Norte', 'Asia', 'Africa', 'Oceania'], correct: [1] },
  { q: 'Qual pais tem a cidade de Lisboa?', opts: ['Espanha', 'Portugal', 'Brasil', 'Franca', 'Italia'], correct: [1] },
  { q: 'A lanterna do telemovel serve para...?', opts: ['Cozinhar', 'Iluminar no escuro', 'Lavar roupa', 'Medir peso'], correct: [1] },
  { q: 'Qual e a capital da Malasia?', opts: ['George Town', 'Kuala Lumpur', 'Johor Bahru', 'Malaca', 'Ipoh'], correct: [1] },
  { q: 'O azeite e comum na dieta do...?', opts: ['Artico so', 'Mediterraneo', 'Siberia so', 'Deserto polar'], correct: [1] },
  { q: 'Qual pais tem a cidade de Montevideu?', opts: ['Argentina', 'Uruguai', 'Paraguai', 'Chile', 'Bolivia'], correct: [1] },
  { q: 'Quantos lados tem um triangulo?', opts: ['2', '3', '4', '5', '6'], correct: [1] },
  { q: 'A capital da Tunisia e...?', opts: ['Sfax', 'Tunes', 'Sousse', 'Bizerte', 'Gabes'], correct: [1] },
  { q: 'Em cozinhas, a frigideira serve para...?', opts: ['Congelar gelo', 'Fritar / saltear', 'Lavar pratos so', 'Guardar livros'], correct: [1] },
  { q: 'Qual pais tem a cidade de Istambul e faz fronteira com a Europa e a Asia?', opts: ['Grecia so', 'Turquia', 'Bulgaria so', 'Georgia so'], correct: [1] },
  { q: 'O peixe e uma fonte comum de...?', opts: ['Proteina', 'Areia', 'Plastico', 'Vidro'], correct: [0] },
  { q: 'Qual e a capital da Bulgaria?', opts: ['Plovdiv', 'Sofia', 'Varna', 'Burgas', 'Ruse'], correct: [1] },
  { q: 'O Wi-Fi em casa permite...?', opts: ['Cozinhar melhor', 'Ligar dispositivos a internet', 'Lavar o chao', 'Abrir portas so'], correct: [1] },
  { q: 'Qual pais tem a cidade de Quito?', opts: ['Peru', 'Equador', 'Colombia', 'Bolivia', 'Chile'], correct: [1] },
  { q: 'A capital da Algeria e...?', opts: ['Oran', 'Argel', 'Constantina', 'Annaba', 'Blida'], correct: [1] },
  { q: 'Em muitos paises, o natal e celebrado em...?', opts: ['Marco', 'Dezembro', 'Julho so', 'Setembro so'], correct: [1] },
  { q: 'Qual pais tem a cidade de Auckland?', opts: ['Australia', 'Nova Zelandia', 'Fiji', 'Papua', 'Samoa'], correct: [1] },
  { q: 'O limao e tipicamente de sabor...?', opts: ['Doce como mel so', 'Acido / azedo', 'Salgado como oceano', 'Amargo de cafe so'], correct: [1] },
  { q: 'Qual e a capital da Eslovaquia?', opts: ['Kosice', 'Bratislava', 'Presov', 'Nitra', 'Zilina'], correct: [1] },
  { q: 'A camara do telemovel serve para...?', opts: ['Fazer fotos e videos', 'Ferver agua', 'Cortar papel', 'Medir vento so'], correct: [0] },
  { q: 'Qual pais tem a cidade de Accra?', opts: ['Nigeria', 'Gana', 'Togo', 'Benim', 'Costa do Marfim'], correct: [1] },
  { q: 'O arroz integral difere do branco sobretudo por...?', opts: ['Ser de plastico', 'Manter mais casca / fibra', 'Ser peixe', 'Ser metal'], correct: [1] },
  { q: 'Qual e a capital da Lituania?', opts: ['Kaunas', 'Vilnius', 'Klaipeda', 'Siauliai', 'Panevezys'], correct: [1] },
  { q: 'Em estradas, o limite de velocidade existe para...?', opts: ['Decoracao', 'Seguranca no transito', 'Enfeite de sinais', 'Vender mais carros so'], correct: [1] },
  { q: 'Qual pais tem a cidade de La Paz (sede de governo)?', opts: ['Peru', 'Bolivia', 'Chile', 'Paraguai', 'Uruguai'], correct: [1] },
  { q: 'A capital da Croacia e...?', opts: ['Split', 'Zagreb', 'Dubrovnik', 'Rijeka', 'Osijek'], correct: [1] },
  { q: 'O ovo e um alimento comum no...?', opts: ['Pequeno-almoco de muitos paises', 'So sobremesa gelada', 'So combustivel', 'So tintas'], correct: [0] },
  { q: 'Qual pais tem a cidade de Casablanca e Rabat como capital?', opts: ['Argelia', 'Marrocos', 'Tunisia', 'Libia', 'Mauritania'], correct: [1] },
  { q: 'Quantos continentes no modelo de 7 continentes?', opts: ['5', '6', '7', '8', '9'], correct: [2] },
  { q: 'A capital da Eslovenia e...?', opts: ['Maribor', 'Liubliana', 'Celje', 'Kranj', 'Koper'], correct: [1] },
  { q: 'Em mercados, a balanca serve para...?', opts: ['Cantar', 'Pesar produtos', 'Cortar cabelo', 'Ligar radio'], correct: [1] },
  { q: 'Qual pais tem a cidade de Harare?', opts: ['Zambia', 'Zimbabue', 'Malawi', 'Botswana', 'Mocambique'], correct: [1] },
  { q: 'O iogurte e feito a partir de...?', opts: ['Leite fermentado', 'Agua com sal so', 'Sumo de laranja so', 'Farinha frita'], correct: [0] },
  { q: 'Qual e a capital da Letonia?', opts: ['Daugavpils', 'Riga', 'Liepaja', 'Jelgava', 'Ventspils'], correct: [1] },
  { q: 'A bandeira vermelha e branca com lua e estrela e da...?', opts: ['Turquia (exemplo classico)', 'Brasil', 'Japao so sol', 'Canada'], correct: [0] },
  { q: 'Qual pais tem a cidade de Lusaka?', opts: ['Zimbabue', 'Zambia', 'Malawi', 'Tanzania', 'Angola'], correct: [1] },
  { q: 'Em escolas, o quadro (ou quadro branco) serve para...?', opts: ['Dormir', 'Escrever e explicar', 'Cozinhar', 'Estacionar'], correct: [1] },
  { q: 'Qual e a capital da Estonia?', opts: ['Tartu', 'Talim', 'Narva', 'Parnu', 'Kohtla-Jarve'], correct: [1] },
  { q: 'O cafe e uma bebida feita de graos torrados de...?', opts: ['Trigo so', 'Cafe', 'Milho so', 'Arroz so', 'Cevada so'], correct: [1] },
  { q: 'Qual pais tem a cidade de Kampala?', opts: ['Quenia', 'Uganda', 'Ruanda', 'Burundi', 'Tanzania'], correct: [1] },
  { q: 'A capital da Georgia (pais no Caucaso) e...?', opts: ['Batumi', 'Tbilisi', 'Kutaisi', 'Rustavi', 'Gori'], correct: [1] },
  { q: 'Em casa, a chave serve normalmente para...?', opts: ['Abrir portas / fechaduras', 'Cortar pao', 'Medir temperatura', 'Ligar a TV so'], correct: [0] },
  { q: 'Qual pais tem a cidade de Abidjan (grande cidade) e Yamoussoukro como capital?', opts: ['Gana', 'Costa do Marfim', 'Togo', 'Benim', 'Liberia'], correct: [1] },
  { q: 'O numero de emergencias em muitos paises da UE e...?', opts: ['123 so', '112', '999 so UK', '911 so EUA', '000'], correct: [1] },
  { q: 'Qual e a capital de Malta?', opts: ['Mdina', 'Valeta', 'Sliema', 'Birkirkara', 'Gozo'], correct: [1] },
  { q: 'A ultima pergunta desta serie: a agua potavel e essencial para...?', opts: ['So decoracao', 'A vida humana', 'So carros', 'So plantas de plastico'], correct: [1] }
];
